import { PdfEccSchemaType } from "../../types";

export const PdfEccInitalValues: PdfEccSchemaType = {
  id: "",
  archdiocese: "",
  hisPhoto: "",
  herPhoto: "",
  city: "",
  parish: "",
  hisName: "",
  hisNickname: "",
  hisBirthdate: "",
  hisProfission: "",
  hisReligion: "",
  herName: "",
  herNickname: "",
  herBirthdate: "",
  herProfission: "",
  herReligion: "",
  marriageReligious: false,
  whichParish: "",
  address: "",
  district: "",
  cep: "",
  cityState: "",
  parishAddress: "",
  addressNumber: "",
  apartmentNumber: "",
  phoneNumber: "",
  hisProfessionalAddress: "",
  hisProfessionalPhoneNumber: "",
  dateWedding: "",
  herProfessionalAddress: "",
  herProfessionalPhoneNumber: "",
  numberOfChildren: "",
  numberFirstStep: "",
  dateFirstStep: "",
  localFirstStep: "",
  activitiesFirstStage: "",
  numberSecondStep: "",
  dateSecondStep: "",
  localSecondStep: "",
  activitiesSecondStage: "",
  numberThirdStep: "",
  dateThirdStep: "",
  localThirdStep: "",
  activitiesThirdStage: "",
  engagementParish: "",
  habilities: "",
  images: {
    her: "",
    his: "",
  },
};
